### ISSUE TITLE
Add Zita-njbridge

### ISSUE THREAD

**Issue by JPenuchot** [omarcostahamido/awesome-networked-media#3]
Very simple CLI tool to bridge Jack and network:
https://kokkinizita.linuxaudio.org/linuxaudio/index.html

**Comment by omarcostahamido** [comment]
Hi Jules,
That looks very interesting.
Would you like to create a Pull Request?
:)

**Comment by JPenuchot** [comment]
There it is !
https://github.com/omarcostahamido/awesome-networked-media/pull/4

**Comment by omarcostahamido** [comment]
super!
